# Generated by Django 2.2.12 on 2020-05-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200501_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='images',
            new_name='image',
        ),
    ]
